### 服务端端口设置
server:
  port: 30001
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/machine?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    show-sql: true
  mvc:
    static-path-pattern: /static/**
#  resources:
#    static-locations:
### Redis (RedisConfiguration)
  redis:
    database: 1         # redis 数据库索引（默认为0）
    host: 127.0.0.1     # redis 服务器ip地址（默认为localhost)
    port: 6379          # redis 端口（默认为6379）
    password:           # redis 访问密码（默认为空）
    timeout: 5000       # redis 连接超时时间（单位毫秒）
    pool:
      max-active: 10    # 最大可用连接数（默认为8，负数表示无限）
      max-idle: 0       # 最大空闲连接数（默认为8，负数表示无限）
      min-idle: 0       # 最小空闲连接数（默认为8，负数表示无限）
      max-wait: -1      # 从连接池中获取连接最大等待时间（默认-1，单位毫秒，负数表示无限）
### mybatis
#mybatis:
#  config-location: classpath:config/mybatis-config.xml
#  mapper-locations: classpath:mappings/**/*.xml
#  type-aliases-package: com.dzxz.teaMachine
#  configuration:
#    map-underscore-to-camel-case: true
